version: '2'

networks:
  app-tier:
    driver: bridge

services:
  activemq:
    image: 'rmohr/activemq:latest'
    networks:
      - app-tier
    ports:
      - '61616:61616'
  producer:
    image: 'activemq-producer:latest'
    networks:
      - app-tier
    depends_on:
      - activemq
    ports:
      - '8020:8020'
  consumer:
    image: 'activemq-consumer:latest'
    networks:
      - app-tier
    depends_on:
      - activemq
    ports:
      - '8010:8010'